" Put all temporary files under the same directory.
"set backup
"set backupdir   =$HOME/.vim/files/vim/backup/
"set backupext   =-vimbackup
"set backupskip  =
"set directory   =$HOME/.vim/files/vim/swap/
"set updatecount =100
"set undofile
"set undodir     =$HOME/.vim/files/vim/undo/
set viminfo     ='100,n$HOME/.vim/files/vim/viminfo

" Disable backup files and viminfo. Keep swap files in the working directory.
set nobackup
"set viminfo     =

" Load common config
source ~/.vim/vimrc-common
